Repository analuciabolico/sgtcc-api, pull requests merged in 2020-11, with the labels that each got.

#2 add test and configuration classes
  src/main/java/com/analuciabolico/sgtccapi/v1/api/boards/BoardController.java
  src/main/resources/application-test.yaml
  src/test/java/com/analuciabolico/sgtccapi/base/ApplicationBase.java
  src/test/java/com/analuciabolico/sgtccapi/v1/api/boards/BoardControllerIT.java
  src/test/java/com/analuciabolico/sgtccapi/v1/api/core/BaseControllerIT.java
  src/test/java/com/analuciabolico/sgtccapi/v1/api/core/BaseUnityTest.java
  src/test/java/com/analuciabolico/sgtccapi/v1/api/core/SqlDocumentProvider.java
Labels: config

#3 Develop
  src/main/java/com/analuciabolico/sgtccapi/v1/api/boards/BoardController.java
  src/main/resources/application-test.yaml
  src/test/java/com/analuciabolico/sgtccapi/base/ApplicationBase.java
  src/test/java/com/analuciabolico/sgtccapi/v1/api/boards/BoardControllerIT.java
  src/test/java/com/analuciabolico/sgtccapi/v1/api/core/BaseControllerIT.java
  src/test/java/com/analuciabolico/sgtccapi/v1/api/core/BaseUnityTest.java
  src/test/java/com/analuciabolico/sgtccapi/v1/api/core/SqlDocumentProvider.java
Labels: develop-master

#11 feat(migrations): Change migrations language from pt-br to en
  plsql/create-sequences.sql
  plsql/create_constraints.sql
  plsql/drop.sql
  plsql/insert.sql
  src/main/resources/db/migration/V1_0/V1_0_0__create_sequences.sql
  src/main/resources/db/migration/V1_0/V1_0_1__create_tables.sql
  src/main/resources/db/migration/V1_0/V1_0_2__create_constraints.sql
Labels: feature

#18 Feat CRUD Students
  .github/workflows/gradle.yml
  src/main/java/com/analuciabolico/sgtccapi/v1/core/models/Person.java
  src/main/java/com/analuciabolico/sgtccapi/v1/core/models/ResourceCreated.java
  src/main/java/com/analuciabolico/sgtccapi/v1/core/validations/GenericMessagesValidationEnum.java
  src/main/java/com/analuciabolico/sgtccapi/v1/core/validations/IGenericMessagesValidation.java
  src/main/java/com/analuciabolico/sgtccapi/v1/core/validations/MessageValidationProperties.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/dtos/StudentRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/model/Student.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/services/implementations/StudentService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/services/interfaces/IStudentService.java
  src/main/resources/validation-messages.properties
Labels: feature

#21 feat#16-title
  src/main/java/com/analuciabolico/sgtccapi/v1/api/titles/TitleController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/model/Teacher.java
  src/main/java/com/analuciabolico/sgtccapi/v1/titles/dtos/TitleRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/titles/model/Title.java
  src/main/java/com/analuciabolico/sgtccapi/v1/titles/repository/TitleRepository.java
  src/main/java/com/analuciabolico/sgtccapi/v1/titles/services/implementations/TitleService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/titles/services/interfaces/ITitleService.java
Labels: feature

#22 Feat/#10
  src/main/java/com/analuciabolico/sgtccapi/v1/api/proposals/ProposalController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/boards/model/Board.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/model/Class.java
  src/main/java/com/analuciabolico/sgtccapi/v1/core/models/Person.java
  src/main/java/com/analuciabolico/sgtccapi/v1/examinations/model/Examination.java
  src/main/java/com/analuciabolico/sgtccapi/v1/proposals/dtos/ProposalRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/proposals/model/Proposal.java
  src/main/java/com/analuciabolico/sgtccapi/v1/proposals/services/implementations/ProposalService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/proposals/services/interfaces/IProposalService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/dtos/StudentRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/model/Student.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/model/Teacher.java
  src/main/resources/application.yaml
Labels: feature

#23 feat#8
  src/main/java/com/analuciabolico/sgtccapi/v1/api/students/StudentController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/api/teachers/TeacherController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/model/Class.java
  src/main/java/com/analuciabolico/sgtccapi/v1/core/models/Person.java
  src/main/java/com/analuciabolico/sgtccapi/v1/proposals/model/Proposal.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/model/Student.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/dtos/TeacherDto.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/dtos/TeacherRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/model/Teacher.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/services/implementations/TeacherService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/services/interfaces/ITeacherService.java
Labels: feature

#24 Feat#9
  src/main/java/com/analuciabolico/sgtccapi/v1/api/classes/ClassController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/api/semesters/SemesterController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/dtos/ClassRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/model/Class.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/repository/ClassRepository.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/services/implementations/ClassService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/services/interfaces/IClassService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/semesters/dtos/SemesterRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/semesters/model/Semester.java
  src/main/java/com/analuciabolico/sgtccapi/v1/semesters/repository/SemesterRepository.java
  src/main/java/com/analuciabolico/sgtccapi/v1/semesters/services/implementations/SemesterService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/semesters/services/interfaces/ISemesterService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/model/Student.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/model/Teacher.java
  src/main/resources/application.yaml
Labels: feature

#25 Feat#12
  plsql/create_tables.sql
  src/main/java/com/analuciabolico/sgtccapi/v1/api/boards/BoardController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/boards/dtos/BoardRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/boards/model/Board.java
  src/main/java/com/analuciabolico/sgtccapi/v1/boards/services/implementations/BoardService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/boards/services/interfaces/IBoardService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/model/Class.java
  src/main/java/com/analuciabolico/sgtccapi/v1/proposals/model/Proposal.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/model/Teacher.java
Labels: feature

#36 feat(interest-area): Add resources to interest area
  src/main/java/com/analuciabolico/sgtccapi/v1/api/interest_areas/InterestAreaController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/interest_areas/dtos/InterestAreaRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/interest_areas/model/InterestArea.java
  src/main/java/com/analuciabolico/sgtccapi/v1/interest_areas/repository/InterestAreaRepository.java
  src/main/java/com/analuciabolico/sgtccapi/v1/interest_areas/services/implementations/InterestAreaService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/interest_areas/services/interfaces/IInterestAreaService.java
Labels: feature

#37 add feature examination.
  src/main/java/com/analuciabolico/sgtccapi/v1/api/examinations/ExaminationController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/boards/model/Board.java
  src/main/java/com/analuciabolico/sgtccapi/v1/examinations/dtos/ExaminationRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/examinations/enums/ExaminationTypeEnum.java
  src/main/java/com/analuciabolico/sgtccapi/v1/examinations/model/Examination.java
  src/main/java/com/analuciabolico/sgtccapi/v1/examinations/repository/ExaminationRepository.java
  src/main/java/com/analuciabolico/sgtccapi/v1/examinations/services/implementations/ExaminationService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/examinations/services/interfaces/IExaminationService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/proposals/model/Proposal.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/model/Student.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/model/Teacher.java
Labels: feature

#40 remove security and add getters/setters in the Requests.
  build.gradle
  src/main/java/com/analuciabolico/sgtccapi/v1/boards/dtos/BoardRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/dtos/ClassRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/interest_areas/dtos/InterestAreaRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/interest_areas/model/InterestArea.java
  src/main/java/com/analuciabolico/sgtccapi/v1/proposals/dtos/ProposalRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/semesters/dtos/SemesterRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/dtos/StudentRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/dtos/TeacherRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/titles/dtos/TitleRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/titles/model/Title.java
  src/main/resources/application.yaml
Labels: config, feature

#42 add feature suggestion.
  src/main/java/com/analuciabolico/sgtccapi/v1/api/suggestions/SuggestionController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/api/teachers/TeacherController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/examinations/model/Examination.java
  src/main/java/com/analuciabolico/sgtccapi/v1/suggestions/dtos/SuggestionRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/suggestions/model/Suggestion.java
  src/main/java/com/analuciabolico/sgtccapi/v1/suggestions/repository/SuggestionRepository.java
  src/main/java/com/analuciabolico/sgtccapi/v1/suggestions/services/implementation/SuggestionService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/suggestions/services/interfaces/ISuggestionService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/model/Teacher.java
Labels: feature

#43 Create readme
  README.md
Labels: documentation

#46 add doc swagger-ui
  src/main/java/com/analuciabolico/sgtccapi/v1/config/SwaggerConfig.java
Labels: documentation

#41 feat(plsql): add function return teacher title
  src/main/java/com/analuciabolico/sgtccapi/v1/api/teachers/TeacherController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/dtos/TeacherTitleResponse.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/model/Teacher.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/repository/TeacherJdbcRepository.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/repository/TeacherRepository.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/services/implementations/TeacherService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/services/interfaces/ITeacherService.java
  src/main/resources/db/migration/V1_0/V1_0_2_add_f_return_teacher_title.sql
Labels: feature, sql

#47 adjustment and add flyway validate migrations.
  src/main/resources/application.yaml
  src/main/resources/db/migration/V1_0/V1_0_1__create_tables.sql
  src/main/resources/db/migration/V1_0/V1_0_3__add_f_return_teacher_title.sql
Labels: feature

#45 feat(plsql): Add procedure return proposal title
  src/main/java/com/analuciabolico/sgtccapi/v1/api/students/StudentController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/dtos/StudentProposalTitleResponse.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/repository/StudentJdbcRepository.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/services/implementations/StudentService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/services/interfaces/IStudentService.java
  src/main/resources/db/migration/V1_0/V1_0_4__add_p_return_proposal_title.sql
Labels: feature

#48 feat(plsql): Create package teacher, function GET_DATE_SCHEDULED_BOARD and BOARDS_AUTHORS
  plsql/f_boards_authors.sql
  plsql/f_get_date_scheduled_board.sql
  plsql/insert.sql
  plsql/pkg_teacher.sql
Labels: feature

#51 add plsql average.
  plsql/p_calculate_and_update_average.sql
  src/main/java/com/analuciabolico/sgtccapi/v1/api/classes/ClassController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/boards/model/Board.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/dtos/ClassAverageRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/dtos/ClassRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/model/Class.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/repository/ClassJdbcRepository.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/services/implementations/ClassService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/services/interfaces/IClassService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/core/exceptions/models/BusinessException.java
  src/main/java/com/analuciabolico/sgtccapi/v1/examinations/dtos/ExaminationRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/examinations/model/Examination.java
  src/main/java/com/analuciabolico/sgtccapi/v1/interest_areas/model/InterestArea.java
  src/main/java/com/analuciabolico/sgtccapi/v1/proposals/dtos/ProposalRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/proposals/model/Proposal.java
  src/main/java/com/analuciabolico/sgtccapi/v1/semesters/model/Semester.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/model/Student.java
  src/main/java/com/analuciabolico/sgtccapi/v1/suggestions/model/Suggestion.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/dtos/TeacherRequest.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/model/Teacher.java
  src/main/java/com/analuciabolico/sgtccapi/v1/titles/model/Title.java
  src/main/resources/application.yaml
  src/main/resources/db/migration/V1_0/V1_0_5__add_p_calculate_and_update_average.sql
Labels: feature

#53 add increment sequences.
  src/main/resources/db/migration/V1_0/V1_0_0__create_sequences.sql
Labels: fix

#54 add fix Json Responses OverFlow.
  plsql/insert.sql
  src/main/java/com/analuciabolico/sgtccapi/v1/boards/model/Board.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/model/Class.java
  src/main/java/com/analuciabolico/sgtccapi/v1/core/models/Person.java
  src/main/java/com/analuciabolico/sgtccapi/v1/examinations/model/Examination.java
  src/main/java/com/analuciabolico/sgtccapi/v1/interest_areas/model/InterestArea.java
  src/main/java/com/analuciabolico/sgtccapi/v1/proposals/model/Proposal.java
  src/main/java/com/analuciabolico/sgtccapi/v1/semesters/model/Semester.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/model/Student.java
  src/main/java/com/analuciabolico/sgtccapi/v1/suggestions/model/Suggestion.java
  src/main/java/com/analuciabolico/sgtccapi/v1/teachers/model/Teacher.java
  src/main/java/com/analuciabolico/sgtccapi/v1/titles/model/Title.java
Labels: fix

#55 Feat/#32 - Return guidance name
  src/main/java/com/analuciabolico/sgtccapi/v1/api/students/StudentController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/dtos/StudentGuidanceResponse.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/repository/StudentJdbcRepository.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/services/implementations/StudentService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/students/services/interfaces/IStudentService.java
  src/main/resources/db/migration/V1_0/V1_0_6__add_p_returns_guidance_name.sql
Labels: feature, sql

#59 add feature route PDF.
  build.gradle
  src/main/java/com/analuciabolico/sgtccapi/v1/api/classes/ClassController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/services/implementations/ClassService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/services/interfaces/IClassService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/core/enums/StudentClassReportColumnEnum.java
  src/main/java/com/analuciabolico/sgtccapi/v1/core/services/implementations/GeneratedReportPdf.java
  src/main/java/com/analuciabolico/sgtccapi/v1/core/services/interfaces/IGeneratedReportPdf.java
  src/main/resources/db/migration/V1_0/V1_0_7__add_p_class_student_report.sql
Labels: feature

#60 Develop
  build.gradle
  src/main/java/com/analuciabolico/sgtccapi/v1/api/classes/ClassController.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/services/implementations/ClassService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/classes/services/interfaces/IClassService.java
  src/main/java/com/analuciabolico/sgtccapi/v1/core/enums/StudentClassReportColumnEnum.java
  src/main/java/com/analuciabolico/sgtccapi/v1/core/services/implementations/GeneratedReportPdf.java
  src/main/java/com/analuciabolico/sgtccapi/v1/core/services/interfaces/IGeneratedReportPdf.java
  src/main/resources/db/migration/V1_0/V1_0_7__add_p_class_student_report.sql
Labels: develop-master
